package: 
    name: xai
    version: "0.0.2"
    
python:
    - 3.6

build:
    number: 1
    script: python setup.py install

about:
    home: https://github.com/EthicalML/xai
    license: MIT
    license_file: LICENSE
    summary: XAI - An eXplainability toolbox for machine learning

extra:
    maintainers:
        - Alejandro Saucedo <a@ethical.institute>

source: 
    git_url: https://github.com/EthicalML/xai
    git_rev: master

channels:
    - conda-forge
    - defaults

requirements:
    build:
        - python
        - setuptools
        - pandas
        - matplotlib
        - numpy
        - scipy
        - scikit-learn
        - python-dateutil==2.5.0
        - pytz==2011k
        - pyparsing==2.0.1
        - cycler==0.10
        - kiwisolver==1.0.1
        - six==1.5

    run:
        - python
        - setuptools
        - pandas
        - matplotlib
        - numpy
        - scipy
        - scikit-learn
        - python-dateutil==2.5.0
        - pytz==2011k
        - pyparsing==2.0.1
        - cycler==0.10
        - kiwisolver==1.0.1
        - six==1.5

