package: 
    name: xai
    version: "0.0.2"
    
python:
    - 3.6

build:
    number: 1
    script: python setup.py install

about:
    home: https://github.com/EthicalML/xai
    license: MIT
    license_file: LICENSE
    summary: XAI - An eXplainability toolbox for machine learning

extra:
    maintainers:
        - Alejandro Saucedo <a@ethical.institute>

source: 
    git_url: https://github.com/EthicalML/xai

channels:
    - conda-forge
    - defaults

requirements:
    build:
        - python >=3.5
        - setuptools
        - pandas==0.23.4
        - matplotlib==3.0.2
        - numpy==1.15.4
        - scipy==1.1.0
        - scikit-learn==0.20.1

    run:
        - python >=3.5
        - setuptools
        - pandas==0.23.4
        - matplotlib==3.0.2
        - numpy==1.15.4
        - scipy==1.1.0
        - scikit-learn==0.20.1

